#ifndef STONE_SYNTAX_DECL_H
#define STONE_SYNTAX_DECL_H

#include "stone/Basic/AddressSpace.h"
#include "stone/Basic/LLVM.h"
#include "stone/Basic/SrcLoc.h"
#include "stone/Diag/DiagnosticArgument.h"
#include "stone/Syntax/DeclContext.h"
#include "stone/Syntax/DeclKind.h"
#include "stone/Syntax/DeclName.h"
#include "stone/Syntax/Identifier.h"
#include "stone/Syntax/Specifier.h"
#include "stone/Syntax/SyntaxAllocation.h"
#include "stone/Syntax/Type.h"
#include "stone/Syntax/TypeAlignment.h"
#include "stone/Syntax/Using.h"

// #include "stone/Syntax/Redeclarable.h"

#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/PointerIntPair.h"
#include "llvm/ADT/PointerUnion.h"
#include "llvm/ADT/iterator.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/PrettyStackTrace.h"
#include "llvm/Support/TrailingObjects.h"
#include "llvm/Support/VersionTuple.h"

#include <algorithm>
#include <iterator>
#include <string>
#include <type_traits>
#include <utility>

namespace stone {
class DiagnosticEngine;
namespace syn {

class Decl;
class Stmt;
class Module;
class BraceStmt;
class DeclContext;
class SyntaxContext;
class ValueDecl;
class VarDecl;
struct SyntaxNode;
class Type;
class Expr;
class ConstructorDecl;
class DestructorDecl;
class TypeAliasDecl;
class ArchetypeKind;
class SyntaxPrinter;
class SyntaxWalker;
class TemplateParameterList;

class DeclStats final : public Stats {
  const Decl &declaration;

public:
  DeclStats(const Decl &declaration)
      : Stats("ast-declaration stats:"), declaration(declaration) {}
  void Print(ColorfulStream &stream) override;
};

using UnifiedContext = llvm::PointerUnion<DeclContext *, SyntaxContext *>;

class alignas(1 << DeclAlignInBits) Decl : public SyntaxAllocation<Decl> {
  friend DeclStats;

  DeclKind kind;
  /// The location of the decl
  SrcLoc loc;
  DeclContext *dc;

  // TODO: UB
  // void *operator new(std::size_t size, const SyntaxContext &ctx,
  //                    DeclContext *parent, std::size_t extra = 0);

public:
  Decl() = delete;
  Decl(const Decl &) = delete;
  Decl(Decl &&) = delete;
  Decl &operator=(const Decl &) = delete;
  Decl &operator=(Decl &&) = delete;

public:
  friend class DeclContext;

  UnifiedContext context;

  /// DeclKind - This indicates which class this is.
  // unsigned declType : 7;

  /// InvalidDecl - This indicates a semantic error occurred.
  // unsigned invalidDecl :  1;

  /// HasAttrs - This indicates whether the decl has attributes or not.
  // unsigned hasAttrs : 1;

  /// Implicit - Whether this declaration was implicitly generated by
  /// the implementation rather than explicitly written by the user.
  // unsigned implicit : 1;

  /// Whether this declaration was "used", meaning that a definition is
  /// required.
  // unsigned used : 1;

public:
  DeclKind GetKind() const { return kind; }
  SrcLoc GetLoc() const { return loc; }

  DeclContext *GetDeclContextForModule() const;

  DeclContext *GetDeclContext() const {
    if (auto dc = context.dyn_cast<DeclContext *>()) {
      return dc;
    }
    return GetDeclContextForModule();
  }

  syn::Module *GetModuleContext() const;

  SyntaxContext &GetSyntaxContext() const {
    auto dc = context.dyn_cast<DeclContext *>();
    if (dc) {
      return dc->GetSyntaxContext();
    }
    return *context.get<SyntaxContext *>();
  }

protected:
  Decl(DeclKind kind, UnifiedContext context) : kind(kind), context(context) {}

protected:
  template <typename DeclTy> friend class Redeclarable;

public:
  bool Walk(SyntaxWalker &walker);
};

class NamedDecl : public Decl {
  /// The name of this declaration, which is typically a normal
  /// identifier but may also be a special ty of name (C++
  /// constructor, etc.)
  DeclName name;
  SrcLoc nameLoc;

protected:
  NamedDecl(DeclKind kind, DeclName name, SrcLoc nameLoc,
            UnifiedContext context)
      : Decl(kind, context), name(name), nameLoc(nameLoc) {}

public:
  /// Get the identifier that names this declaration, if there is one.
  ///
  /// This will return NULL if this declaration has no name (e.g., for
  /// an unnamed class) or if the name is a special name such ast a C++
  /// constructor.
  Identifier *GetIdentifier() const { return name.GetAsIdentifier(); }

  /// Get the name of identifier for this declaration as a StringRef.
  ///
  /// This requires that the declaration have a name and that it be a simple
  /// identifier.
  llvm::StringRef GetNameText() const {
    // TODO: assert(name.IsIdentifier() && "Name is not a simple identifier");
    return GetIdentifier() ? GetIdentifier()->GetName() : "";
  }
  void SetDeclName(DeclName name) { this->name = name; }
  DeclName GetDeclName() { return name; }

  void SetDeclNameLoc(SrcLoc nameLoc) { this->nameLoc = nameLoc; }
  SrcLoc GetDeclNameLoc() { return nameLoc; }
};

// class ForwardDecl : public NamedDecl {
// public:
// };

class TypeDecl : public NamedDecl /*TODO: AnyDecl, ForwardDecl*/ {

  friend class SyntaxContext;
  /// This indicates the Type object that represents
  /// this TypeDecl.  It is a cache maintained by
  /// ASTContext::getTypedefType, ASTContext::getTagDeclKind, and
  /// ASTContext::getTemplateTypeParmType, and TemplateTypeParmDecl.

  mutable const Type *typeForDecl = nullptr;

  /// The start of the source range for this declaration.
  SrcLoc startLoc;

protected:
  TypeDecl(DeclKind kind, Identifier name, SrcLoc nameLoc,
           UnifiedContext context)
      : NamedDecl(kind, name, nameLoc, context) {}

public:
  // Low-level accessor. If you just want the type defined by this node,
  // check out ASTContext::getTypeDeclType or one of
  // ASTContext::getTypedefType, ASTContext::getRecordType, etc. if you
  // already know the specific kind of node this is.
  const Type *GetTypeForDecl() const { return typeForDecl; }
  void SetTypeForDecl(const Type *TD) { typeForDecl = TD; }

  // SourceLocation GetBeginSrcLoc() const LLVM_READONLY { return LocStart; }
  // void SetStartSrcLoc(startSrcLoc L) { LocStart = L; }
};

// TODO: May use this instead of using NamedDecl
class ValueDecl : public NamedDecl {
  QualType qualType;

public:
  ValueDecl(DeclKind kind, DeclName name, SrcLoc nameLoc,
            UnifiedContext context)
      : NamedDecl(kind, name, nameLoc, context) {}

public:
  void SetQualType(QualType qt) { this->qualType = qt; }
  QualType GetQualType() { return qualType; }
};

// class LabelDecl : public NamedDecl {
// public:
// };

// class SpaceDecl : public NamedDecl {
// public:
//   SpaceDecl(DeclContext *dc, SrcLoc loc, DeclName name)
//       : NamedDecl(DeclKind::Space, dc, loc, name) {}
// };

/// Abstract class describing generic type parameters and associated types,
/// whose common purpose is to anchor the abstract type parameter and specify
/// requirements for any corresponding type argument.
// class AbstractTypeParamDecl : public NamedDecl {
// protected:
//   AbstractTypeParamDecl(DeclKind kind, DeclContext *dc, Identifier name,
//                         SourceLoc NameLoc)
//     : NamedDecl(kind, dc, name, NameLoc, { }) { }

// public:
//   /// Retrieve the set of protocols to which this abstract type
//   /// parameter conforms.
//   llvm::ArrayRef<ProtocolDecl *> GetConformingInterfacess() const;

//   static bool classof(const Decl *D) {
//     return D->getKind() >= DeclKind::First_AbstractTypeParamDecl &&
//            D->getKind() <= DeclKind::Last_AbstractTypeParamDecl;
//   }
// };

// A private class for forcing exact field layout.
// class alignas(8) GenericContextBase {
//   // Not really public. See GenericContext.
// public:
//   llvm::PointerIntPair<GenericParamList *, 1, bool> genericParamsAndBit;

//   /// The trailing where clause.
//   ///
//   /// Note that this is not currently serialized, because semantic analysis
//   /// moves the trailing where clause into the generic parameter list.
//   TrailingWhereClause *trailingWhere = nullptr;

//   /// The generic signature of this declaration.
//   llvm::PointerIntPair<GenericSignature, 1, bool> genericSigAndBit;
// };

// class GenericContext : private GenericContextBase, public DeclContext {
//   // friend class GenericParamListRequest;
//   // friend class GenericSignatureRequest;

// protected:
//   GenericContext(DeclContextKind declContextKind, DeclContext *parentDC,
//                  GenericParamList *genericParams);
// };


class GenericTypeDecl : public TypeDecl {

};



class AccessControl {
  // This also belongs to struct
  AccessLevel level;

public:
  void SetAccessLevel(AccessLevel level) { this->level = level; }
  AccessLevel GetAccessLevel() { return level; }
};

// This is really your function prototye
class FunctionDecl
    : public DeclContext,
      public ValueDecl,
      public AccessControl /*, public syn::Redeclarable<FunctionDecl>*/ {

  /// This enum member is active if GetBodyKind() is BodyKind::Parsed or
  /// BodyKind::TypeChecked.
  BraceStmt *body;

  StorageSpecifierKind storageSpecifierKind;

public:
  FunctionDecl(DeclKind kind, DeclName name, SrcLoc nameLoc,
               DeclContext *parent)
      : DeclContext(DeclContextKind::Decl, parent),
        ValueDecl(kind, name, nameLoc, parent) {}

public:
  BraceStmt *GetBody(bool canSynthesize = true) const;
  /// Set a new body for the function.
  void SetBody(BraceStmt *body);

  void SetStorageSpecifierKind(StorageSpecifierKind ssk) {
    this->storageSpecifierKind = ssk;
  }
  StorageSpecifierKind GetStorageSpecifierKind() {
    return storageSpecifierKind;
  }

  // void SetReturnType(TypeDecl* tyDecl);

public:
};

/// Standalone function: fun F0() -> void {}
class FunDecl : public FunctionDecl {
  // TODO: You should aonly pass SyntaxContext and DeclContext
  SrcLoc funLoc;
  bool hasLBrace;

public:
  FunDecl(DeclName name, SrcLoc nameLoc, DeclContext *parent)
      : FunctionDecl(DeclKind::Fun, name, nameLoc, parent) {}

public:
  bool IsMain() const;

  /// True if the function is a defer body.
  bool IsDeferBody() const;

  bool IsStatic() const;

  bool IsMember() const;

  // TODO: Think about
  bool IsForward() const;

  bool HasReturn() const;

  void SetFunLoc(SrcLoc funLoc);
  SrcLoc GetFunLoc() { return funLoc; }

  void WithLeftBrace();
  bool HasLeftBrace();

  QualType GetReturnType() const;

public:
  // void SetReturnType(TypeDecl* returnTy);

  // SrcLoc GetStaticLoc() const { return staticLoc; }
  // SrcLoc GetFunLoc() const { return funcLoc; }

  static bool classof(const Decl *d) { return d->GetKind() == DeclKind::Fun; }
  static bool classof(const FunctionDecl *d) {
    return classof(static_cast<const Decl *>(d));
  }
  static bool classof(const DeclContext *dc) {
    if (auto d = dc->GetAsDecl())
      return classof(d);
    return false;
  }
};

// Member functions: fun Particle::Fire() -> bool ...
// class MemberFunDecl : public FunDecl {
// public:
//   MemberFunDecl(SyntaxContext &tc, DeclContext *dc, SrcLoc funLoc,
//               DeclName name, SrcLoc nameLoc, StorageKind sk)
//        : FunDecl(DeclKind::Fun, tc, dc, dn, dnLoc, st) {}

// public:
//   bool IsStatic() const;
//   bool IsInstance() const { return !IsStatic(); }
// };

class NominalTypeDecl : public TypeDecl,
                        public DeclContext,
                        public AccessControl {
public:
  bool IsForward() const;
};

class StructDecl final : public NominalTypeDecl {
public:
  static bool classof(const Decl *d) {
    return d->GetKind() == DeclKind::Struct;
  }
};

class InterfaceDecl final : public NominalTypeDecl {
public:
  static bool classof(const Decl *d) {
    return d->GetKind() == DeclKind::Interface;
  }
};

class EnumDecl final : public NominalTypeDecl {
public:
  static bool classof(const Decl *d) { return d->GetKind() == DeclKind::Enum; }
};

class BlockDecl : public Decl, public DeclContext {};

class ConstructorInitializer final {
public:
};

// class ConstructorDecl : public MemberDecl {
// public:
// };

// class DestructorDecl : public MemberDecl {
// public:
// };

class TemplateDecl : public NamedDecl {
public:
};

class UsingDecl final : public NamedDecl {
  SrcLoc usingLoc;
  UsingKind usingKind;

public:
  // syn::Module *mod = nullptr;
};

class TrustDecl final
    : public Decl,
      public llvm::TrailingObjects<TrustDecl, TemplateParameterList *> {};

} // namespace syn
} // namespace stone
#endif
